In [1]:
import numpy as np

In [2]:
fpath=r"C:\Users\sathw\Downloads\tipsf.csv"

In [3]:
x = np.genfromtxt(fpath,delimiter=',',skip_header=True)
x

array([[  0.  ,  16.99,   1.01, ...,   1.  ,   0.  ,   2.  ],
       [  1.  ,  10.34,   1.66, ...,   1.  ,   0.  ,   3.  ],
       [  2.  ,  21.01,   3.5 , ...,   1.  ,   0.  ,   3.  ],
       ...,
       [241.  ,  22.67,   2.  , ...,   0.  ,   0.  ,   2.  ],
       [242.  ,  17.82,   1.75, ...,   0.  ,   0.  ,   2.  ],
       [243.  ,  18.78,   3.  , ...,   2.  ,   0.  ,   2.  ]])

#### 1) what is the total bill value?

In [4]:
total_bill = np.sum(x[:,1]) 
total_bill

4827.77

#### 2) what is the total tip value?

In [5]:
sum_tip_value = x[:,2]
sum_tip_value

array([ 1.01,  1.66,  3.5 ,  3.31,  3.61,  4.71,  2.  ,  3.12,  1.96,
        3.23,  1.71,  5.  ,  1.57,  3.  ,  3.02,  3.92,  1.67,  3.71,
        3.5 ,  3.35,  4.08,  2.75,  2.23,  7.58,  3.18,  2.34,  2.  ,
        2.  ,  4.3 ,  3.  ,  1.45,  2.5 ,  3.  ,  2.45,  3.27,  3.6 ,
        2.  ,  3.07,  2.31,  5.  ,  2.24,  2.54,  3.06,  1.32,  5.6 ,
        3.  ,  5.  ,  6.  ,  2.05,  3.  ,  2.5 ,  2.6 ,  5.2 ,  1.56,
        4.34,  3.51,  3.  ,  1.5 ,  1.76,  6.73,  3.21,  2.  ,  1.98,
        3.76,  2.64,  3.15,  2.47,  1.  ,  2.01,  2.09,  1.97,  3.  ,
        3.14,  5.  ,  2.2 ,  1.25,  3.08,  4.  ,  3.  ,  2.71,  3.  ,
        3.4 ,  1.83,  5.  ,  2.03,  5.17,  2.  ,  4.  ,  5.85,  3.  ,
        3.  ,  3.5 ,  1.  ,  4.3 ,  3.25,  4.73,  4.  ,  1.5 ,  3.  ,
        1.5 ,  2.5 ,  3.  ,  2.5 ,  3.48,  4.08,  1.64,  4.06,  4.29,
        3.76,  4.  ,  3.  ,  1.  ,  4.  ,  2.55,  4.  ,  3.5 ,  5.07,
        1.5 ,  1.8 ,  2.92,  2.31,  1.68,  2.5 ,  2.  ,  2.52,  4.2 ,
        1.48,  2.  ,

In [6]:
np.sum(x[:,2])

731.5799999999999

#### 3) count how many sunday,saturday,thursday,friday, are there?

In [7]:
np.unique(x[:,5])

array([0., 1., 2., 3.])

In [8]:
np.unique(x[:,5], return_counts= True)

(array([0., 1., 2., 3.]), array([87, 76, 62, 19], dtype=int64))

#### 4) how many smokers are there?

In [9]:
np.unique(x[:,4])

array([0., 1.])

In [10]:
np.unique(x[:,4], return_counts=True) #ns-0 #s-1 

(array([0., 1.]), array([151,  93], dtype=int64))

#### 5) what is the avg tip given by the female and male?

In [11]:
gender = (x[:,3])
tip = (x[:,2])
tip_by_male = np.mean(tip[gender==0])
print('the avg tip given by male :', tip_by_male)
tip_by_female = np.mean(tip[gender==1])
print('the avg tip given by male :', tip_by_female)

the avg tip given by male : 2.8334482758620685
the avg tip given by male : 3.0896178343949043


#### 6)how much amount have been spent by female and males?

In [12]:
total_bill = (x[:,1])
tip = (x[:,2])
gender = (x[:,3])

amount_by_males = np.sum(total_bill[gender==0]) #1570
tip_by_males = np.sum(tip[gender==0])
total_spent_by_males = amount_by_males + tip_by_males
print('total amount spent by males :', total_spent_by_males)

amount_by_females = np.sum(total_bill[gender==1]) #1570
tip_by_females = np.sum(tip[gender==1])
total_spent_by_females = amount_by_females + tip_by_females
print('total amount spent by females :', total_spent_by_females)

total amount spent by males : 1817.4599999999996
total amount spent by females : 3741.89


#### 7) what is the min and max tip given?

In [13]:
tip = x[:,2]
min_tip = np.min(tip)
print('the minimum tip given is :', min_tip)

max_tip = np.max(tip)
print('the maximum tip given is :', max_tip)

the minimum tip given is : 1.0
the maximum tip given is : 10.0


#### 8) how many male & female are going for dinner and lunch?

In [14]:
gender = x[:,3]
time = x[:,6] #lunch

male_lunch = np.sum((gender == 0) & (time == 0))
female_lunch = np.sum((gender == 1) & (time == 0))
print("No of males went for lunch :", male_lunch )
print("No of females went for lunch :",female_lunch)

male_dinner = np.sum((gender == 0) & (time == 1))
female_dinner = np.sum((gender == 1) & (time == 1))
print("No of males went for Dinner :", male_dinner )
print("No of female went for Dinner :",female_dinner)

No of males went for lunch : 52
No of females went for lunch : 124
No of males went for Dinner : 35
No of female went for Dinner : 33


#### 9) find out the average size?

In [15]:
averaze_size = np.mean(x[:,7])
print('the average size is :', averaze_size)

the average size is : 2.569672131147541


#### 10) how many female smokers are there and male smokers are there?

In [16]:
gender = x[:,3]
smokers = x[:,4]
male_smokers = np.sum((gender==0) & (smokers==1))
print('No of male smokers :', male_smokers)

female_smokers = np.sum((gender==1) & (smokers==1))
print('No of female smokers :',female_smokers)

No of male smokers : 33
No of female smokers : 60
